[build]
  publish = "."

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/images/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
